<!DOCTYPE html>
<%@page import="java.util.List"%>
<%@page import="java.util.ArrayList"%>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Generate new meldoy from your midi file using ai tensorflow">
    <meta name="keywords" content=" ">
    <meta name="author" content="Anish nath">
    <meta name="robots" content="index,follow" />
	<meta name="googlebot" content="index,follow" />
	<meta name="resource-type" content="document" />
	<meta name="classification" content="tools" />
	<meta name="language" content="en" />

    <title>Generate new melody</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/blog-post.css" rel="stylesheet">
    
	
	<link href="css/MIDIPlayer.css" rel="stylesheet" type="text/css" />
	<!-- shim -->
	<script src="inc/shim/Base64.js" type="text/javascript"></script>
	<script src="inc/shim/Base64binary.js" type="text/javascript"></script>
	<script src="inc/shim/WebAudioAPI.js" type="text/javascript"></script>
	<script src="inc/shim/WebMIDIAPI.js" type="text/javascript"></script>
	<!-- jasmid package -->
	<script src="inc/jasmid/stream.js"></script>
	<script src="inc/jasmid/midifile.js"></script>
	<script src="inc/jasmid/replayer.js"></script>
	<!-- midi.js package -->
	<script src="js/midi/audioDetect.js" type="text/javascript"></script>
	<script src="js/midi/gm.js" type="text/javascript"></script>
	<script src="js/midi/loader.js" type="text/javascript"></script>
	<script src="js/midi/plugin.audiotag.js" type="text/javascript"></script>
	<script src="js/midi/plugin.webaudio.js" type="text/javascript"></script>
	<script src="js/midi/plugin.webmidi.js" type="text/javascript"></script>
	<script src="js/midi/player.js" type="text/javascript"></script>
	<script src="js/midi/synesthesia.js" type="text/javascript"></script>
	<!-- utils -->
	<script src="js/util/dom_request_xhr.js" type="text/javascript"></script>
	<script src="js/util/dom_request_script.js" type="text/javascript"></script>
	<!-- includes -->
	<script src="./inc/timer.js" type="text/javascript"></script>
	<script src="./inc/colorspace.js" type="text/javascript"></script>
	<script src="./inc/event.js" type="text/javascript"></script>
	
	<link rel="stylesheet" href="css/croppie.css" />
    <script src="js/croppie.min.js"></script>
	
	
		<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "Article",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://8gwifi.org/docs/kube-nginx.jsp"
  },
  "name" : "Deploying Secure HTTPS NGINX in Kubernetes",
  "author" : {
    "@type" : "Person",
    "name" : "Anish"
  },
  "headline": "Deploying Secure HTTPS NGINX in Kubernetes",
  "image":"https://8gwifi.org/docs/img/kube-nginx.png",
  "datePublished" : "2018-08-15",
  "dateModified": "2018-08-15",
  "articleSection" : "Deploying Secure HTTPS NGINX in Kubernetes",
  "articleBody" : [ "Definition of Modern TLS","nginx certs and Keys","kubernetes Create Secrets", "kubernetes View Secrets", "Modern TLS nginx configuration", "inotifywait" ,"ConfigMaps","nginx-app.yaml" , "kubectl get service nginxsvc"],
  "publisher" : {
    "@type" : "Organization",
    "name" : "8gwifi.org Tech Blog",
    "logo" :  {
      "@type": "ImageObject",
      "url": "https://8gwifi.org/docs/img/logo.jpg"
    }
  }
}
</script>




  </head>

  <body>
  
  

  
  <script type="text/javascript">
	if (typeof (console) === "undefined") var console = {
		log: function() {}
	};
	// Toggle between Pause and Play modes.
	var pausePlayStop = function(stop) {
		var d = document.getElementById("pausePlayStop");
		if (stop) {
			MIDI.Player.stop();
			d.src = "./images/play.png";
		} else if (MIDI.Player.playing) {
			d.src = "./images/play.png";
			MIDI.Player.pause(true);
		} else {
			d.src = "./images/pause.png";
			MIDI.Player.resume();
		}
	};
	eventjs.add(window, "load", function(event) {
		var link = document.createElement("link");
		link.href = "//fonts.googleapis.com/css?family=Oswald";
		link.ref = "stylesheet";
		link.type = "text/css";
		document.body.appendChild(link);
		var link = document.createElement("link");
		link.href = "//fonts.googleapis.com/css?family=Andada";
		link.ref = "stylesheet";
		link.type = "text/css";
		document.body.appendChild(link);
		
		/// load up the piano keys
		var colors = document.getElementById("colors");
		var colorElements = [];
		/* for (var n = 0; n < 88; n++) {
			var d = document.createElement("b ");
			d.innerHTML = MIDI.noteToKey[n + 21];
			d.class = "mt-4";
			colorElements.push(d);
			colors.appendChild(d);
		}  */
		///
		MIDI.loader = new sketch.ui.Timer;
		MIDI.loadPlugin({
			soundfontUrl: "./soundfont/",
			onprogress: function(state, progress) {
				MIDI.loader.setValue(progress * 100);
			},
			onsuccess: function() {
				/// this is the language we are running in
				var title = document.getElementById("title");
				title.innerHTML = "Sound being generated with " + MIDI.api + " " + JSON.stringify(MIDI.supports);

				/// this sets up the MIDI.Player and gets things going...
				player = MIDI.Player;
				player.timeWarp = 1; // speed the song is played back
				player.loadFile(song[songid++ % song.length], player.start);

				/// control the piano keys colors
				var colorMap = MIDI.Synesthesia.map();
				player.addListener(function(data) {
					var pianoKey = data.note - 21;
					var d = colorElements[pianoKey];
					if (d) {
						if (data.message === 144) {
							var map = colorMap[data.note - 27];
							if (map) d.style.background = map.hex;
							d.style.color = "#ggf";
						} else {
							d.style.background = "";
							d.style.color = "";
						}
					} 
				}); 
				///
				//ColorSphereBackground();
				MIDIPlayerPercentage(player);
			}
		});
	});

	var MIDIPlayerPercentage = function(player) {
		// update the timestamp
		var time1 = document.getElementById("time1");
		var time2 = document.getElementById("time2");
		var capsule = document.getElementById("capsule");
		var timeCursor = document.getElementById("cursor");
		//
		eventjs.add(capsule, "drag", function(event, self) {
			eventjs.cancel(event);
			player.currentTime = (self.x) / 420 * player.endTime;
			if (player.currentTime < 0) player.currentTime = 0;
			if (player.currentTime > player.endTime) player.currentTime = player.endTime;
			if (self.state === "down") {
				player.pause(true);
			} else if (self.state === "up") {
				player.resume();
			}
		});
		//
		function timeFormatting(n) {
			var minutes = n / 60 >> 0;
			var seconds = String(n - (minutes * 60) >> 0);
			if (seconds.length == 1) seconds = "0" + seconds;
			return minutes + ":" + seconds;
		};
		player.getNextSong = function(n) {
			var id = Math.abs((songid += n) % song.length);
			player.loadFile(song[id], player.start); // load MIDI
		};
		player.setAnimation(function(data, element) {
			var percent = data.now / data.end;
			var now = data.now >> 0; // where we are now
			var end = data.end >> 0; // end of song
			if (now === end) { // go to next song
				var id = ++songid % song.length;
				player.loadFile(song[id], player.start); // load MIDI
			}
			// display the information to the user
			timeCursor.style.width = (percent * 100) + "%";
			time1.innerHTML = timeFormatting(now);
			time2.innerHTML = "-" + timeFormatting(end - now);
		});
	};
	
	var ColorSphereBackground = function() {
		var d = document;
		var canvas = document.createElement("canvas");
		var ctx = canvas.getContext("2d");
		canvas.style.cssText = "position: fixed; left: 0; top: 0; opacity: 1";
		canvas.style.width = window.innerWidth + "px";
		canvas.style.height = window.innerHeight + "px";
		document.body.appendChild(canvas);
		//
		eventjs.add(window, "resize", function() {
			canvas.style.width = window.innerWidth + "px";
			canvas.style.height = window.innerHeight + "px";
			ctx.drawImage(theSphere = sphere(percent), 0, 0)
		});
		eventjs.add(d, "scroll", function(e) {
			var percent = 1 - document.body.scrollTop / document.body.scrollHeight;
			ctx.drawImage(theSphere = sphere(percent), 0, 0);
			onMouseMove();
		});
		var theSphere;
		var px = window.innerWidth / 2;
		var py = window.innerHeight / 2;
		var onMouseMove = function(event) {
			ctx.drawImage(theSphere, 0, 0);
			if (event) {
				var coords = eventjs.proxy.getCoord(event);
				coords.x -= document.body.scrollLeft;
				coords.y -= document.body.scrollTop;
				px = coords.x;
				py = coords.y;
			} else { // 
				var coords = {
					x: px,
					y: py
				};
			}
			//
			var x = (coords.x / window.innerWidth) * 255 - 127; // grab mouse pixel coords, center at midpoint
			var y = (coords.y / window.innerHeight) * 255 - 127;
			var imageData = ctx.getImageData(0, 0, canvas.width, canvas.height); // get image data
			var data = imageData.data;
			for (var n = 0, length = data.length; n < length; n += 4) {
				data[n] = data[n] + x - y; // red (control left)
				data[n + 1] = data[n + 1] - x - y; // green (control right)
				data[n + 2] = data[n + 2] + y + y; // blue (control down)
			}
			ctx.putImageData(imageData, 0, 0);
		};
		eventjs.add(d, "mousemove", onMouseMove);
		///
		function sphere(top) { // create Sphere image, and apply to <canvas>
			var canvas1 = document.createElement("canvas");
			var ctx = canvas1.getContext("7d");
			var w = 75;
			var left = -20;
			var top = top * -50;
			canvas.width = canvas1.width = w * window.innerWidth / window.innerHeight;
			canvas.height = canvas1.height = w;
			ctx.fillRect(0, 0, window.innerWidth, window.innerHeight);
			n = 360;
			while (n--) { // go through hues
				var x = left + w;
				var y = top + w;
				var g = ctx.createLinearGradient(x, top, x, y);
				g.addColorStop(0, "#000");
				g.addColorStop(.5, "hsl(" + ((n + 60) % 360) + ",100%,50%)");
				g.addColorStop(1, "#FFF");
				ctx.beginPath(); // draw triangle
				ctx.moveTo(x, top);
				ctx.lineTo(x, y);
				ctx.lineTo(x + 2, y);
				ctx.lineTo(x + 5, top);
				ctx.fillStyle = g; // apply gradient
				ctx.fill();
				ctx.translate(x, y); // rotate + translate into position
				ctx.rotate((1 / 360) * Math.PI * 2);
				ctx.translate(-x, -y);
			}
			return canvas1;
		};
		//
		var percent = 1 - document.body.scrollTop / document.body.scrollHeight;
		ctx.drawImage(theSphere = sphere(percent), 0, 0)
	};
	
	// Begin loading indication.
	var player;
	// MIDI files from Disklavier World
	var songid = 0;
	
	<%
	
	System.out.println("Anish");
	
	List<String> songArray =  new ArrayList();
	
	songArray.add("data:audio/mid;base64,TVRoZAAAAAYAAQACAYBNVHJrAAAAUwD/Aw1jb250cm9sIHRyYWNrAP8BCWNyZWF0b3I6IAD/AR5HTlUgTGlseVBvbmQgMi4xOC4yICAgICAgICAgICAA/1gEBAISCAD/UQMPQkAA/y8ATVRyawAAAD4A/wMFXG5ldzoAsAdkAJBIWoMAkEgAAJBKWoMAkEoAAJBMWoMAkEwAAJBNWoMAkE0AAJBPWoMAkE8AAP8vAA==");
	songArray.add("data:audio/mid;base64,TVRoZAAAAAYAAQACAYBNVHJrAAAAUwD/Aw1jb250cm9sIHRyYWNrAP8BCWNyZWF0b3I6IAD/AR5HTlUgTGlseVBvbmQgMi4xOC4yICAgICAgICAgICAA/1gEBAISCAD/UQMPQkAA/y8ATVRyawAAAD4A/wMFXG5ldzoAsAdkAJBIWoMAkEgAAJBKWoMAkEoAAJBMWoMAkEwAAJBNWoMAkE0AAJBPWoMAkE8AAP8vAA==");
	songArray.add("data:audio/mid;base64,TVRoZAAAAAYAAQACAYBNVHJrAAAAUwD/Aw1jb250cm9sIHRyYWNrAP8BCWNyZWF0b3I6IAD/AR5HTlUgTGlseVBvbmQgMi4xOC4yICAgICAgICAgICAA/1gEBAISCAD/UQMPQkAA/y8ATVRyawAAAD4A/wMFXG5ldzoAsAdkAJBIWoMAkEgAAJBKWoMAkEoAAJBMWoMAkEwAAJBNWoMAkE0AAJBPWoMAkE8AAP8vAA==");
	
	
	
	%>
	
	var song = []
	
	<%
	int i= 0;
	for ( i = 0; i < songArray.size(); i++) {
		String x = songArray.get(i);
		%>
		song.push('<%=x%>');
		
	<%}%>
	
	console.log(song[1])
</script>

    <!-- Navigation -->
 	<%@ include file="navigation.jsp"%>

    <!-- Page Content -->
    <div class="container">
    
    
    

      <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">

          <!-- Title -->
          <h1 class="mt-4">Create new Melody </h1>
          
          <form action="#" method="post" enctype="multipart/form-data">
     <label for="uploadMidi">Upload Your Midi File</label>
     <div class="form-group">
  <input type="file" id="file">
  <input type="submit" value="upload">
  </div>
</form>

          <!-- Author -->
         <!--  <p class="lead">
            by
            <a href="https://www.linkedin.com/in/anishnath">Anish</a>
            <p>Posted on Tuesday August 15, 2018</p>
          </p> -->
          
         <!--  <img class="img-fluid rounded" src="img/kube-nginx.png" height="400" width="500" alt="Referefce "> -->
          
          <%@ include file="footer_adsense.jsp"%>
           <%@ include file="analytics.jsp"%>
           
     
	
	

          
        <div>
		<div class="player">
			<div>
				<input type="image" src="./images/pause.png"  value="pause" onclick="pausePlayStop()" id="pausePlayStop">
				<input type="image" src="./images/stop.png"  value="stop" onclick="pausePlayStop(true)">
				<input type="image" src="./images/backward.png" value="stop" onclick="player.getNextSong(-1);">
				<input type="image" src="./images/forward.png"  value="stop" onclick="player.getNextSong(+1);">
			</div>
			<div class="time-controls">
				<span id="time1" class="time">0:00</span>
				<span id="capsule">
					<span id="cursor"></span>
				</span>
				<span id="time2" class="time" style="text-align: left;">-0:00</span>
			</div>
		</div>
	<div id="title">Loading API...</div>
	 <div id="colors"></div> 
		
		
	</div>
	<p>Your Meldoy </p>
	
	
	<div id="id_1"><audio controls="">
              <source controls="" src="data:audio/mid;base64,TVRoZAAAAAYAAQACAYBNVHJrAAAAUwD/Aw1jb250cm9sIHRyYWNrAP8BCWNyZWF0b3I6IAD/AR5HTlUgTGlseVBvbmQgMi4xOC4yICAgICAgICAgICAA/1gEBAISCAD/UQMPQkAA/y8ATVRyawAAAD4A/wMFXG5ldzoAsAdkAJBIWoMAkEgAAJBKWoMAkEoAAJBMWoMAkEwAAJBNWoMAkE0AAJBPWoMAkE8AAP8vAA==" type="audio/wav">
              Your browser does not support the audio element.
            </audio></div>
	
	<audio src="midi/first1.midi"></audio>
	
	<div class="embed-responsive embed-responsive-21by9">
  <iframe class="embed-responsive-item" src="images/generated/first_1.png"></iframe>
</div>

<p>Your Meldoy Modified-1</p>

<div class="embed-responsive embed-responsive-21by9">
  <iframe class="embed-responsive-item" src="images/generated/2019-06-19_084347_01_1.png"></iframe>
</div>

<p>Your Meldoy Modified-2 </p>

<div class="embed-responsive embed-responsive-21by9">
  <iframe class="embed-responsive-item" src="images/generated/2019-06-19_084347_04_1.png"></iframe>
</div>
	






<%@ include file="thanks.jsp"%>


<hr>


      <!-- Comments Form -->
    

          <!-- Single Comment -->
 

          <!-- Comment with nested comments -->
        
          

        </div>

		
        
        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

          <!-- Ad Widget -->
         <%@ include file="footer_adsense.jsp"%> 

          
         
         
         <!-- Topic Widget -->
         <%@ include file="side.jsp"%>
         
           <!-- Add Comments Support -->
         
         
         

        </div>

      </div>
      <!-- /.row -->


	<%@ include file="addcomments.jsp"%>
    
    </div>
    
    
    
    
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; notemusic.site 2019</p>
      </div>
      <!-- /.container -->
    </footer>
    

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>


  </body>

</html>