<!DOCTYPE html>
<%@page import="java.util.Iterator"%>
<%@page import="java.util.List"%>
<%@page import="java.util.ArrayList"%>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="view and play midi sequence in txt">
    <meta name="keywords" content="midi to txt, midi to notsequence, parse midi file in JSON ">
    <meta name="author" content="Anish nath">
    <meta name="robots" content="index,follow" />
	<meta name="googlebot" content="index,follow" />
	<meta name="resource-type" content="document" />
	<meta name="classification" content="tools" />
	<meta name="language" content="en" />
	
	 
	 

    <title>view and play midi sequence in txt</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/blog-post.css" rel="stylesheet">
    
    <script type="text/javascript" src="https://unpkg.com/tone@13.4.9/build/Tone.js"></script>
	<script type="text/javascript" src="https://unpkg.com/@tonejs/ui@0.0.8/build/tonejs-ui.js"></script>
	<script type="text/javascript" src="https://unpkg.com/@tonejs/midi"></script>
    
    
    
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "Article",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "http://notemusic.site/parsemidi.jsp"
  },
  "name" : "Parse Midi file to list of notes with length and starting time",
  "author" : {
    "@type" : "Person",
    "name" : "Anish"
  },
  "headline": "Parse Midid file to JSON",
  "image":"http://notemusic.site/images/1.png",
  "datePublished" : "2019-06-30",
  "dateModified": "2019-06-30",
  "articleSection" : "view and play midi sequence in txt",
  "articleBody" : [ "view and play midi sequence in txt,to list of notes with length and starting time"],
  "publisher" : {
    "@type" : "Organization",
    "name" : "notemusic.site ",
    "logo" :  {
      "@type": "ImageObject",
      "url": "http://notemusic.site/parsemidi.jsp"
    }
  }
}
</script>

<%@ include file="analytics.jsp"%>




  </head>

  <body>
  
  <style type="text/css">

		#FileDrop{
			position: relative;
			width: 100%;
			height: 100px;
			border: 2px dashed black;
			color: black;
			margin: 20px auto;
		}

		#FileDrop.Hover{
			background-color: black;
			color: white;
		}

		#FileDrop input {
			position: absolute;
			width: 100%;
			height: 100%;
			opacity: 0;
			left: 0px;
			top: 0px;
		}

		#FileDrop #Text {
			position: absolute;
			width: 100%;
			height: 20px;
			line-height: 20px;
			left: 0px;
			top: 50%;
			transform: translate(0, -50%);
			text-align: center;
		}

		textarea {
			font-family: monospace;
			height: 300px;
			width: 100%;
			display: inline-block;
			position: relative;
			float: left;
		}

		#Results {
			position: relative;
			width: 100%;
			margin: 10px auto;
		}

		#Description {
			position: relative;
			width: 100%;
			text-align: center;
			height: 40px;
			font-size: 16px;
			margin: 10px auto;
			font-family: sans-serif;
		}

		tone-play-toggle {
			margin-top: 10px;
		}

	</style>
  
  

  
  

    <!-- Navigation -->
 	<%@ include file="navigation.jsp"%>

    <!-- Page Content -->
    <div class="container">
    
    
    

      <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">

          <!-- Title -->
          <h1 class="mt-4">Convert MIDI file to list of notes with length and starting time</h1>
          


			
	<tone-content>
		<div id="Description">Parse a MIDI file into a Tone.js-friendly JSON format.</div>
		<div id="FileDrop">
			<div id="Text">
				Drop a midi file here
			</div>
			<input type="file" accept="audio/midi">
		</div>
		<div id="Results">
			<textarea class="form-control" id="ResultsText" placeholder="json output..."></textarea>
		</div>
		<tone-play-toggle disabled></tone-play-toggle>
	</tone-content>


	<script type="text/javascript">


		if (!(window.File && window.FileReader && window.FileList && window.Blob)) {
			document.querySelector("#FileDrop #Text").textContent = "Reading files not supported by this browser";
		} else {

			const fileDrop = document.querySelector("#FileDrop")

			fileDrop.addEventListener("dragenter", () => fileDrop.classList.add("Hover"))

			fileDrop.addEventListener("dragleave", () => fileDrop.classList.remove("Hover"))

			fileDrop.addEventListener("drop", () => fileDrop.classList.remove("Hover"))

			document.querySelector("#FileDrop input").addEventListener("change", e => {
				//get the files
				const files = e.target.files
				if (files.length > 0){
					const file = files[0]
					document.querySelector("#FileDrop #Text").textContent = file.name
					parseFile(file)
				}
			})
		}

		let currentMidi = null

		function parseFile(file){
			//read the file
			const reader = new FileReader()
			reader.onload = function(e){
				const midi = new Midi(e.target.result)
				document.querySelector("#ResultsText").value = JSON.stringify(midi, undefined, 2)
				document.querySelector('tone-play-toggle').removeAttribute('disabled')
				currentMidi = midi
			}
			reader.readAsArrayBuffer(file)
		}

		const synths = []
		document.querySelector('tone-play-toggle').addEventListener('play', (e) => {
			const playing = e.detail
			if (playing && currentMidi){
				const now = Tone.now() + 0.5
				currentMidi.tracks.forEach(track => {
					//create a synth for each track
					const synth = new Tone.PolySynth(10, Tone.Synth, {
						envelope : {
							attack : 0.02,
							decay : 0.1,
							sustain : 0.3,
							release : 1
						}
					}).toMaster()
					synths.push(synth)
					//schedule all of the events
					track.notes.forEach(note => {
						synth.triggerAttackRelease(note.name, note.duration, note.time + now, note.velocity)
					})
				})
			} else {
				//dispose the synth and make a new one
				while(synths.length){
					const synth = synths.shift()
					synth.dispose()
				}
			}
		})

	</script>
    
  
          
          <%@ include file="footer_adsense.jsp"%>
           <%@ include file="analytics.jsp"%>
           
     
	
	

          
       




<%@ include file="thanks.jsp"%>


<hr>


      <!-- Comments Form -->
    

          <!-- Single Comment -->
 

          <!-- Comment with nested comments -->
        
          

        </div>

		
        
        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

          <!-- Ad Widget -->
         <%@ include file="footer_adsense.jsp"%> 

          
         
         
         <!-- Topic Widget -->
         <%@ include file="side.jsp"%>
         
           <!-- Add Comments Support -->
         
         
         

        </div>

      </div>
      <!-- /.row -->


	<%@ include file="addcomments.jsp"%>
    
    </div>
    
    
    
    
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; notemusic.site 2019</p>
      </div>
      <!-- /.container -->
    </footer>
    

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>


  </body>

</html>